# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Godt' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Network

  pod 'ObjectMapper’, ‘3.1.0’
  pod 'Alamofire', ‘4.6.0’
  pod 'AlamofireImage', ‘3.3.0’

  # Pods for Godt

end
